### ISSUE TITLE
content/intro

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/EEweb#3]
- [ ] 三大重點
- [ ] 老師資料區, 抽取成模板出來
- [ ] 課程重點(三學分... 那些不重要的資訊)

**Comment by andrewchen30** [comment]
老師還沒給清楚資料
否則最後就是我們隨便寫

**Comment by Dobubu** [comment]
就先用老師資料區好了 ， 那張紙(老師自己手寫的自我介紹)有在你那齁?

**Comment by andrewchen30** [comment]
有的 那個我到時候處理 那個頁面是我做的
