### ISSUE TITLE
intro page 完成

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/EEweb#30]
- [x] 老師資料
- [x] 課程介紹
- [x] 三大重點版面調整
- [x] 三大重點資料&照片

@Dobubu  我需要你選三張照片給我

**Comment by andrewchen30** [comment]
@Dobubu 幫我補上以下資料
- [x] 老師資料 (貼上來在 Github 給我即可)
- [x] 三大重點的圖片 (選三張覺得適合的, 直接去 intro.jade 修改)
  弄完後跟我說

**Comment by Dobubu** [comment]
### 老師資料

學歷:
美國德州奧斯汀大學 英語教學碩士
國立政治大學西洋語文學系學士
台北市立第一女子高級中學畢業

經歷:
亞東技術學院專任英文講師
台灣科技大學兼任英文講師

獲獎紀錄:
104學年度教育部補助技專推動通識課革新計劃
103學年度教學單位教學優良獎
101學年度優良教材、教具教學評選-教材編撰(大二英文)佳作
98學年度 教學優良獎

教學專長:
廣泛閱讀教學
英語文學習單教學
