### ISSUE TITLE
課程清單

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/EEweb#31]
- [x] 清單
- [x] 參與學生名單

@Dobubu  麻煩你給我資料路徑

**Comment by Dobubu** [comment]
參與學生名單路徑 
https://drive.google.com/open?id=0B0vV7I93ATWcRVI3MG1aY21XdHM

**Comment by andrewchen30** [comment]
@Dobubu 
麻煩幫我補上 studentList 組別
測試用的端點 `http://localhost:8080/nameList`

**Comment by Dobubu** [comment]
課程清單路徑
https://drive.google.com/open?id=1KBgbKKTy0yM-yYMXRyTR4OL86GGYpdS0FsEJaPLimFg

**Comment by Dobubu** [comment]
[柏安10022015.zip](https://github.com/PolarBearAndrew/EEweb/files/67722/10022015.zip)
